In [40]:
import os
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
from postgreSQLpassword import passW
import time

In [41]:
arr='2019-03'

connection_string = "postgresql://postgres:"+passW+"@localhost:5432/ecobici"
engine = create_engine(connection_string)

filedir=f'./EcoBiciData/Trips/{arr}.csv'
EcoBiciDf=pd.read_csv(filedir, low_memory=False)
EcoBiciDf=EcoBiciDf.rename(str.lower, axis='columns')
EcoBiciDf = EcoBiciDf.drop('unnamed: 9', 1)
mo=EcoBiciDf['fecha_retiro'].str.slice(start=3,stop=5)
da=EcoBiciDf['fecha_retiro'].str.slice(start=0,stop=2)
ye=EcoBiciDf['fecha_retiro'].str.slice(start=6,stop=10)
EcoBiciDf['fecha_retiro']=ye+"-"+mo+"-"+da
EcoBiciDf['fecha_retiro']

mo=EcoBiciDf['fecha_arribo'].str.slice(start=3,stop=5)
da=EcoBiciDf['fecha_arribo'].str.slice(start=0,stop=2)
ye=EcoBiciDf['fecha_arribo'].str.slice(start=6,stop=10)
EcoBiciDf['fecha_arribo']=ye+"-"+mo+"-"+da
EcoBiciDf['fecha_arribo']

EcoBiciDf.iloc[113432,6]="10"
EcoBiciDf.iloc[113432,7]="2019-03-06"
EcoBiciDf.iloc[113432,8]="08:32:11"

EcoBiciDf.to_sql('ecobicidf', con=engine, if_exists="append", index = False)
EcoBiciDf.dtypes

EcoBiciDf.head()

,genero_usuario,edad_usuario,bici,ciclo_estacion_retiro,fecha_retiro,hora_retiro,ciclo_estacion_arribo,fecha_arribo,hora_arribo
0,M,34,8861,143,2019-03-01,00:00:54,68,2019-03-01,00:13:55
1,F,33,2601,51,2019-03-01,00:01:01,53,2019-03-01,00:07:16
2,M,25,8257,340,2019-03-01,00:01:26,324,2019-03-01,00:09:26
3,M,32,15007,139,2019-03-01,00:01:42,155,2019-03-01,00:06:20
4,F,22,7601,81,2019-03-01,00:01:50,75,2019-03-01,00:06:22